-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 11:32:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `emigo_registry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emigo_id` VARCHAR(64) NOT NULL DEFAULT '',
  `handle` VARCHAR(128) NULL,
  `registry` VARCHAR(256) NOT NULL DEFAULT '',
  `created` INT(64) NOT NULL,
  `updated` INT(64) NOT NULL,
  `revision` INT NOT NULL,
  `message` TEXT(65535) NOT NULL,
  `signature` VARCHAR(4096) NOT NULL,
  `pubkey` VARCHAR(4096) NOT NULL,
  `pubkey_type` VARCHAR(32) NOT NULL,
  `blocked` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `emigo_id_UNIQUE` (`emigo_id` ASC),
  UNIQUE INDEX `handle_UNIQUE` (`handle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` INT(32) NOT NULL,
  `processor` INT NOT NULL,
  `memory` BIGINT(64) NOT NULL,
  `storage` BIGINT(64) NOT NULL,
  `requests` BIGINT(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `config_id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `string_value` VARCHAR(1024) NULL,
  `num_value` BIGINT(64) NULL,
  `bool_value` TINYINT NULL,
  UNIQUE INDEX `config_id_UNIQUE` (`config_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

