/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.coredb.registry.api;

import org.coredb.registry.model.Registry;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@Api(value = "info", description = "the info API")
public interface InfoApi {

    @ApiOperation(value = "", nickname = "getRegistry", notes = "Retrieve server details", response = Registry.class, tags={ "info", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "sucessful operation", response = Registry.class) })
    @RequestMapping(value = "/info/registry",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Registry> getRegistry();

}
