# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build frontend of registry app server
      - name: Build frontent
        run: |
          cd fe
          npm install
          npm install @angular/cli
          npm run-script ng build -- --prod --base-href /app/
          
      # Build backend of registry app server
      - name: Build backend
        run: |
          cd be
          mvn -B verify # -B batch mode makes Maven less verbose
          mvn install -DskipTests
          
      # Export installer for registry app server
      - name: Export installer
        run: |
          rm -rf export
          mkdir -p export
          bash tools/assemble $GITHUB_RUN_NUMBER '0'

      # Export installer
      - name: Export
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: export 
